name: Build and deploy ASP.Net Core app to Azure Web App - resume-builder-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'  # or your target .NET version

      - name: Build with dotnet
        run: dotnet build ./resume_builder_api/resume_builder_api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./resume_builder_api/resume_builder_api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # required for JWT token
      contents: read # required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8063ACF54126472996E446E1612ED03F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9B01AEAB3A9142C59C112A8728C6BB08 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E04CB20428334BA89208E6E0F15B619F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'resume-builder-api'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
